package org.howard.edu.lsp.finale.question1;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/**
 * JUnit test suite for PasswordGeneratorService (based off final doc)
 */
public class PasswordGeneratorServiceTest {

    private PasswordGeneratorService service;
    /**
     * Setup method executed before each test
     * Gets singleton instance of PasswordGeneratorService and resets algorithm
    */
    @BeforeEach
    public void setup() {
        service = PasswordGeneratorService.getInstance();
        // clears the current algorithm 
        service.setAlgorithm(null);
    }
    
    /**
     * Verifies that singleton instance is not null
     */
    @Test
    public void checkInstanceNotNull() {
        // verify that 'service' is not null
        assertNotNull(service, "getInstance() should not return null");
    }

    /**
     * Verify that getInstance() returns the same singleton instance
     */
    @Test
    public void checkSingleInstanceBehavior() {
        PasswordGeneratorService second = PasswordGeneratorService.getInstance();
        // Verify both references point to the exact same instance (singleton identity)
        assertTrue(service == second, "Both references must be the exact same instance");
    }

    
    /**
     * Verifies that generatePassword throws IllegalStateExeception 
     * if called before algorithm was selected
     */
    @Test
    public void generateWithoutSettingAlgorithmThrowsException() {
        PasswordGeneratorService s = PasswordGeneratorService.getInstance();
        s.setAlgorithm(null); // ensure no algorithm selected
        assertThrows(IllegalStateException.class, () -> s.generatePassword(8),
                "generatePassword should throw IllegalStateException when no algorithm is selected");
    }

    /**
     * Verifies that basic algorithm generated a password 
     * that holds the correct length and contains only digits 
     */
    @Test
    public void basicAlgorithmGeneratesCorrectLengthAndDigitsOnly() {
        service.setAlgorithm("basic");
        String p = service.generatePassword(10);
        assertNotNull(p);
        assertEquals(10, p.length(), "Password length must match requested length");
        assertTrue(p.matches("\\d{10}"), "Basic algorithm must generate digits only");
    }

    /**
     * Verifies that the enhanced algorithm generates a password
     * that holds the correct length and contains alphanumeric characters 
     */
    @Test
    public void enhancedAlgorithmGeneratesCorrectCharactersAndLength() {
        service.setAlgorithm("enhanced");
        String p = service.generatePassword(12);
        assertNotNull(p);
        assertEquals(12, p.length(), "Password length must match requested length");
        assertTrue(p.matches("[A-Za-z0-9]{12}"), "Enhanced algorithm must generate alphanumeric characters only");
    }

    /**
     * Verifies that letters algorithm generates a password 
     * that holds the correct length and contains only letters
     */
    @Test
    public void lettersAlgorithmGeneratesLettersOnly() {
        service.setAlgorithm("letters");
        String p = service.generatePassword(8);
        assertNotNull(p);
        assertEquals(8, p.length(), "Password length must match requested length");
        assertTrue(p.matches("[A-Za-z]{8}"), "Letters algorithm must generate letters only");
    }

    /**
     * Verifies that switching algorithms correctly changes password generation 
     * checking - basic, letters, enhanced algorithms
     */
    @Test
    public void switchingAlgorithmsChangesBehavior() {
        service.setAlgorithm("basic");
        String p1 = service.generatePassword(10);

        service.setAlgorithm("letters");
        String p2 = service.generatePassword(10);

        service.setAlgorithm("enhanced");
        String p3 = service.generatePassword(10);

        // p1 digits only
        assertTrue(p1.matches("\\d{10}"), "After setting basic, password should be digits only");

        // p2 letters only
        assertTrue(p2.matches("[A-Za-z]{10}"), "After setting letters, password should contain letters only");

        // p3 alphanumeric
        assertTrue(p3.matches("[A-Za-z0-9]{10}"), "After setting enhanced, password should be alphanumeric");

        // Extra sanity: ensure they are not all identical (extremely unlikely)
        boolean allEqual = p1.equals(p2) && p2.equals(p3);
        assertFalse(allEqual, "Passwords generated by different algorithms should not all be identical");
    }
}
